import path from "path";
import fs from "fs";
import { Agency } from "../src/types.js";

const FILE_PATH = path.join(process.cwd(), "data", "stored_agencies.json");

const SEED_AGENCIES: Agency[] = [
  {
    id: "agency-general-1",
    name: "شركة تراست جروب للتوظيف",
    phone: "01000234561",
    address: "شارع مصطفى النحاس، مدينة نصر، القاهرة",
    description: "تراست جروب من المكاتب الممتازة والشهيرة في إلحاق العمالة المصرية بالخارج وتوفير المقابلات المباشرة مع اللجان السعودية والخليجية لكافة التخصصات.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1KywnpW7g6/?mibextid=wwXIfr",
    email: "cv@trustgroup-eg.com",
    whatsapp: "https://wa.me/201000234561",
    trustedByOwner: false
  },
  {
    id: "agency-general-2",
    name: "شركة جوب واي للتوظيف الطبي",
    phone: "01122334455",
    address: "المنيل، القاهرة",
    description: "مؤسسة طبية متخصصة ومصنفة بالدرجة الأولى لتوفير أرقى الفرص المتاحة للأطباء البشريين والأسنان والصيادلة والتمريض في كبرى المجمعات الطبية والمستشفيات بالسعودية.",
    rating: 4.9,
    reviews: [],
    facebook: "https://www.facebook.com/share/1GY8z6dVsn/?mibextid=wwXIfr",
    email: "recruitment@jobway-medical.com",
    whatsapp: "https://wa.me/201122334455",
    trustedByOwner: false
  },
  {
    id: "agency-general-3",
    name: "شركة استدامة للتوظيف",
    phone: "01555443322",
    address: "الدقي، الجيزة",
    description: "واحدة من المكاتب المتميزة في استقطاب وتعيين الكوادر الهندسية والفنية والحرفية بالخليج العربي ومتابعة ممتازة للرواتب وحقوق العاملين.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/share/16K4p6qkhi/?mibextid=wwXIfr",
    email: "hr@estidama-eg.com",
    whatsapp: "https://wa.me/201555443322",
    trustedByOwner: false
  },
  {
    id: "agency-general-4",
    name: "شركة هورايزون للتوظيف",
    phone: "0237651234",
    address: "المهندسين، الجيزة",
    description: "شركة هورايزون مرخصة رسميًا ومشهورة بسد الاحتياجات الوظيفية للشركات السعودية خصوصًا في قطاع المقاولات، المحاسبة، وتكنولوجيا المعلومات.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/share/16RpKeXe6Q/?mibextid=wwXIfr",
    email: "jobs@horizon-hr.com",
    whatsapp: "https://wa.me/201007651234",
    trustedByOwner: false
  },
  {
    id: "agency-general-5",
    name: "شركة كادر للتوظيف بالخارج",
    phone: "01099112233",
    address: "جامعة الدول العربية، المهندسين، الجيزة",
    description: "متخصصة في إلحاق الكوادر المهنية والتعليمية والإدارية لكبرى المدارس والشركات بالمملكة العربية السعودية والإمارات وقطر.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/kaderrecruitment/",
    email: "cv@kader-rec.com",
    whatsapp: "https://wa.me/201099112233",
    trustedByOwner: false
  },
  {
    id: "agency-general-6",
    name: "شركة السجيني لتوظيف الكفاءات",
    phone: "01144005522",
    address: "مصر الجديدة، القاهرة",
    description: "شركة رائدة ومرخصة رسمياً بالتعاون المباشر مع الهيئات الحكومية والخاصة بالخليج لتأمين عقود لحديثي الخبرة والمحترفين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/elseginyrec/",
    email: "info@elseginy-rec.com",
    whatsapp: "https://wa.me/201144005522",
    trustedByOwner: false
  },
  {
    id: "agency-general-7",
    name: "شركة روافد الخليج للتوظيف",
    phone: "01277889900",
    address: "طنطا، الغربية",
    description: "توفير مقابلات مستمرة وتعاقدات مؤمنة للمهندسين والمدرسين بجميع مناطق المملكة العربية السعودية بكل سهولة ومصداقية.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/Rawafid.gulf.eg/",
    email: "jobs@rawafid-gulf.com",
    whatsapp: "https://wa.me/201277889900",
    trustedByOwner: false
  },
  {
    id: "agency-general-8",
    name: "شركة الشارقة للحاق العمالة",
    phone: "01522001144",
    address: "الدقي، الجيزة",
    description: "تركز على قطاعات الضيافة، التشغيل والصيانة، وتضم باقة مميزة من أخصائيي الأغذية والمشروبات والمحاسبين للمطاعم الكبرى بجدة والرياض.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/ElSharqiaCompany/",
    email: "apply@sharjah-eg.com",
    whatsapp: "https://wa.me/201522001144",
    trustedByOwner: false
  },
  {
    id: "agency-trusted-1",
    name: "شركة الطائف للتوظيف",
    phone: "0233042111",
    address: "77 شارع سوريا، المهندسين، الجيزة",
    description: "إحدى كبرى الشركات المرخصة وأوسعها انتشاراً، إشراف ومصداقية تامة في تجهيز مقابلات المعلمين والأطباء والمهندسين. من أفضل البيئات الموثوق والآمنة للتعامل.",
    rating: 4.9,
    reviews: [
      {
        id: "rev-eltaef-1",
        userName: "أحمد منصور (معلم حاسب)",
        rating: 5,
        comment: "سافرت معهم والحمد لله شركة محترمة وأصحابها في غاية الأمانة والوضوح والالتزام.",
        date: "2026-05-20"
      }
    ],
    facebook: "https://www.facebook.com/share/1ZFyLpySWY/?mibextid=wwXIfr",
    email: "info@eltaef.com",
    whatsapp: "https://wa.me/201002345611",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-2",
    name: "شركة المعالي جروب للتوظيف",
    phone: "01000004561",
    address: "21 شارع السخاوي، روكسي، مصر الجديدة، القاهرة",
    description: "من أعرق مكاتب التوظيف في مصر (رخصة 466)، متفردة بتعاوناتها الاستراتيجية لخدمة القطاع الطبي والتعليمي، التزام كامل ببنود العقود وحقوق المرشحين.",
    rating: 4.9,
    reviews: [
      {
        id: "rev-elmaaly-1",
        userName: "م. محمد الغديري",
        rating: 5,
        comment: "المعالي غنية عن التعريف وأصحابها ناس أفاضل يراعون الله في كل المسافرين والتعاقدات.",
        date: "2026-06-02"
      }
    ],
    facebook: "https://www.facebook.com/share/1WWqWkbmZ7/?mibextid=wwXIfr",
    email: "elmaaly@elmaalygroup.net",
    whatsapp: "https://wa.me/201000004561",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-3",
    name: "شركة انفراد للتوظيف",
    phone: "01022340567",
    address: "شارع القصر العيني، القاهرة",
    description: "شركة انفراد صاحبة سمعة ذهبية وخبرة استثنائية في انتقاء وإلحاق الكفاءات بمختلف القطاعات الهندسية والإدارية والمالية. نوصي بها لصدق المعاملة والشفافية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/enfrad.hr1",
    email: "cv@enfrad-hr.com",
    whatsapp: "https://wa.me/201022340567",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-4",
    name: "شركة آل زيدان للتوظيف",
    phone: "01233445566",
    address: "المعادي، القاهرة",
    description: "إدارة محترفة متخصصة في توثيق العلاقات الخليجية وتأمين عقود وظيفية ممتازة لحديثي وذوي الخبرة بمختلف دول الخليج العربي.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1ExjNEQbF5/?mibextid=wwXIfr",
    email: "info@alzeidan-rec.com",
    whatsapp: "https://wa.me/201233445566",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-5",
    name: "شركة مسار للتوظيف",
    phone: "01144556677",
    address: "شارع جامعة الدول، المهندسين، الجيزة",
    description: "مجموعات مسار المعتمدة توفر أرقى المقابلات والنزاهة والتدقيق الممتاز للأخصائيين ومحاسبين التكاليف بقطاع التجزئة والمقاولات في مصر والخليج.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/19gPvHW6fL/?mibextid=wwXIfr",
    email: "jobs@masar-rec.com",
    whatsapp: "https://wa.me/201144556677",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-6",
    name: "شركة أبو عالية للتوظيف",
    phone: "01007788991",
    address: "مصر الجديدة، القاهرة",
    description: "شركة مرخصة معتمدة بخبرة عالية ومتابعة شخصية ودقيقة لكل إجراءات السفر، ممتازة جدًا لراغبي الفرص الحقيقية والمثبتة رسميًا.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Dv6zUY1Sj/?mibextid=wwXIfr",
    email: "rec@aboalia-hr.com",
    whatsapp: "https://wa.me/201007788991",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-7",
    name: "شركة السلسبيل للتوظيف",
    phone: "01222883311",
    address: "وسط البلد، القاهرة",
    description: "مصداقية عالية للغاية في استلام وتأمين كافة أنواع التأشيرات والوظائف التخصصية بالمملكة ككل، معاملتهم محترمة وسريعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1EJFF8wYre/?mibextid=wwXIfr",
    email: "cv@elsalsabeel.com",
    whatsapp: "https://wa.me/201222883311",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-8",
    name: "شركة جوب هانتر للتوظيف",
    phone: "01099887766",
    address: "عباس العقاد، مدينة نصر، القاهرة",
    description: "تمتلك عقودًا حصرية وشراكات ضخمة مع أرقى الهيئات الطبية والتجارية والمقاولات في السعودية والخليج، تتميز بالأمانة والسرعة الفائقة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1CWhR3QHW7/?mibextid=wwXIfr",
    email: "apply@jobhunter-eg.com",
    whatsapp: "https://wa.me/201099887766",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-9",
    name: "شركة أرتك للتوظيف",
    phone: "01122888800",
    address: "الدقي، الجيزة",
    description: "مؤسسة مرموقة تقدم خدمات استشارية وجمع الكفاءات الطبية والتعليمية والمهنية، خدماتها نزيهة ومواعيدها دقيقة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1D7GLQXEt4/?mibextid=wwXIfr",
    email: "recruitment@artec-hr.com",
    whatsapp: "https://wa.me/201122888800",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-10",
    name: "شركة العاصمة للتوظيف",
    phone: "0225112233",
    address: "رمسيس، وسط القاهرة",
    description: "تقدم حلول توظيف ممتازة بوضوح تام، وتتابع العقد بدقة لضمان حصول المرشح على حقوق الراتب والسكن والتأمين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/17KeRKA7cP/?mibextid=wwXIfr",
    email: "hr@capital-rec.com",
    whatsapp: "https://wa.me/20225112233",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-11",
    name: "شركة رواد الخليج للتوظيف",
    phone: "01011223344",
    address: "شبرا، القاهرة",
    description: "من المكاتب المعتمدة رسمياً والتي يتابع أصحابها الكرام كل صغيرة وكبيرة لخدمة المسافر، متخصصة في الفئات الطبية والتعليمية والسائقين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1FDmBbKYLy/?mibextid=wwXIfr",
    email: "jobs@ruwwad-khaleej.com",
    whatsapp: "https://wa.me/201011223344",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-12",
    name: "شركة محمد سعد للتوظيف",
    phone: "01511223344",
    address: "حلوان، القاهرة",
    description: "إدارة موثوقة ومحترمة تهتم بكل المرشحين وتضمن مطابقة الراتب المتفق عليه وتعمل بأمانة تامة ومصداقية يشهد لها الجميع.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/profile.php?id=61551200990707",
    email: "rec@saadgroup-eg.com",
    whatsapp: "https://wa.me/201511223344",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-13",
    name: "شركة الركن الملكي للتوظيف",
    phone: "01033445588",
    address: "الجيزة، مصر",
    description: "توفير كامل الدعم للمسافرين وتواجد مستمر للإجابة على استفسارات العملاء بكل احترام ومصداقية ودعم مهني كامل.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Bbbr9qYCL/?mibextid=wwXIfr",
    email: "apply@royalcorner-hr.com",
    whatsapp: "https://wa.me/201033445588",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-14",
    name: "شركة معالينا للتوظيف",
    phone: "01155006622",
    address: "شبرا الخيمة، القليوبية",
    description: "أخلاق معتمدة وإدارة موثوقة تسهل جميع الإجراءات وبأقل عمولات مستحقة دون مبالغة وشروط مطابقة للعقد.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1P71MkM5vu/?mibextid=wwXIfr",
    email: "cv@maalina.net",
    whatsapp: "https://wa.me/201155006622",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-15",
    name: "شركة بايونير للتوظيف",
    phone: "01077665544",
    address: "شارع الهرم، الجيزة",
    description: "بايونير لتوفير الكفاءات بالخارج، مشهود لها بالدقة الفنية ومراعاة الشروط القانونية الصارمة لحقوق الكوادر المسافرة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/14Ky85m6BMq/?mibextid=wwXIfr",
    email: "cv@pioneer-hr.com",
    whatsapp: "https://wa.me/201077665544",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-16",
    name: "شركة منارة الخليج للتوظيف",
    phone: "01211155566",
    address: "المنصورة، الدقهلية",
    description: "إحدى الشركات المعتمدة والرائدة تاريخياً في توفير عقود مميزة للأطباء بكبرى مستشفيات المملكة بجميع المناطق.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BEzZKbnES/?mibextid=wwXIfr",
    email: "medical@manarat-khaleej.com",
    whatsapp: "https://wa.me/201211155566",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-17",
    name: "شركة الملتقى للتوظيف",
    phone: "01099881122",
    address: "مصر الجديدة، القاهرة",
    description: "خدمات ممتازة وفريق عمل متعاون يسعى لتحقيق مصلحة المرشح بكل أمانة ووضوح ويسهل إجراءات الفحص والجامعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/17c36KBqB3/?mibextid=wwXIfr",
    email: "cv@almoltaqa-rec.com",
    whatsapp: "https://wa.me/201099881122",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-18",
    name: "شركة الفنار للتوظيف",
    phone: "0237339488",
    address: "27 شارع مصدق، الدقي، الجيزة",
    description: "من الأسماء الرائدة تاريخيًا بمصر، التزام كامل ومصداقية لا متناهية ومقابلات على أعلى مستوى مع كبرى الإدارات التعليمية والطبية بالخليج.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1EvGtB9iRL/?mibextid=wwXIfr",
    email: "recruitment@alfanarjob.com",
    whatsapp: "https://wa.me/201026002931",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-19",
    name: "شركة النخبة للتوظيف",
    phone: "01000667788",
    address: "مصر الجديدة، القاهرة",
    description: "شركة استشارية ممتازة لتوظيف الكفاءات بجميع تخصصات التعليم والقطاع الهندسي والصحة، رعاية ومساندة كاملة للمرشح في الفحص والتعاقد.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/16xYbfrvFV/?mibextid=wwXIfr",
    email: "info@elnokhba.co",
    whatsapp: "https://wa.me/2010000667788",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-20",
    name: "شركة أجادة للتوظيف",
    phone: "01122336699",
    address: "مدينة نصر، القاهرة",
    description: "مكتب عريق شعاره الإجادة والأمانة العملية، يقدم فرصًا متميزة للغاية بتعاقدات وتسهيلات رائعة تضمن راحة تامة طيلة فترة التواجد بالخارج.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BvpQ6Dm6j/?mibextid=wwXIfr",
    email: "apply@ejada-gulf.com",
    whatsapp: "https://wa.me/201122336699",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-21",
    name: "شركة رويال للتوظيف",
    phone: "01055566677",
    address: "المعادي، القاهرة",
    description: "رويال للتوظيف، تلتزم بأعلى معايير المصداقية ولديهم تواصل وتعاون رائع لراحة المسافرين وضمان تنفيذ شروط الاتفاقية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/14L9kYSx6PE/?mibextid=wwXIfr",
    email: "cv@royal-rec.com",
    whatsapp: "https://wa.me/201055566677",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-22",
    name: "شركة المجموعة الدولية للتوظيف",
    phone: "01288998811",
    address: "فيصل، الجيزة",
    description: "توفير كامل الدعم الفني والحرفي والمهني وسائقي النقل الثقيل والمبيعات بدقة ومصداقية وحسن تعامل مع كافة المرشحين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1D7HGm8S28/?mibextid=wwXIfr",
    email: "info@int-group.com.eg",
    whatsapp: "https://wa.me/201288998811",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-23",
    name: "شركة دار الخبرة للتوظيف",
    phone: "01522330044",
    address: "مصر الجديدة، القاهرة",
    description: "أصحابها ناس أفاضل يتقون الله في شروط العقود والتعامل، رائدة في الكفاءات الهندسية ورعاية المشاريع وتسهيل أمور السفر.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/16K9ZRrjTy/?mibextid=wwXIfr",
    email: "cv@darelexebera.com",
    whatsapp: "https://wa.me/201522330044",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-24",
    name: "شركة سما جروب للتوظيف",
    phone: "01122446688",
    address: "المنيل، القاهرة",
    description: "إدارة محترمة ونسعى في توفير التسهيلات اللازمة والمقابلات العادلة للأخصائيين والمعلمين والتمريض بأمانة لا غبار عليها.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BHt1hHkkX/?mibextid=wwXIfr",
    email: "hr@sama-rec.com",
    whatsapp: "https://wa.me/201122446688",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-25",
    name: "شركة شاشة للتوظيف",
    phone: "01022448800",
    address: "المهندسين، الجيزة",
    description: "صاحبة باقة متميزة من المقابلات وسرعة الفحص في السفر المباشر لكبرى كافيهات ومطاعم وفنادق ومجمعات وصيدليات الرياض والدمام.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BWQ5Ys1AV/?mibextid=wwXIfr",
    email: "shasha.cv@shasha-hr.com",
    whatsapp: "https://wa.me/201022448800",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-26",
    name: "شركة البكري للتوظيف",
    phone: "01233669911",
    address: "شبرا، القاهرة",
    description: "إدارة رائدة وصاحبة مصداقية تامة، يتابعون الشكاوى باحتراف وممتازين للتعاون مع الأطباء والصيادلة والمهندسين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Bokx8TfL7/?mibextid=wwXIfr",
    email: "cv@albakry.com.eg",
    whatsapp: "https://wa.me/201233669911",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-27",
    name: "شركة وش السعد للتوظيف",
    phone: "01000443355",
    address: "وسط البلد، القاهرة",
    description: "من الأسماء المحترمة والشهيرة ولديهم دقة في تسهيل المعاملات وسجل ممتاز في إنجاح مقابلات السفر بكل أمانة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/16stAEsR9V/?mibextid=wwXIfr",
    email: "info@wesh-elsaad-gulf.com",
    whatsapp: "https://wa.me/2010000443355",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-28",
    name: "شركة المواهب للتوظيف",
    phone: "01588772211",
    address: "الهرم، الجيزة",
    description: "مجموعات محترمة لتوفير كفاءات التشغيل واللوجستيات والمقاولات والسائقين والمطاعم مع ضمان الراتب والامتيازات كاملة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BhF93W6do/?mibextid=wwXIfr",
    email: "hr@talents-eg.com",
    whatsapp: "https://wa.me/201588772211",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-29",
    name: "شركة غرناطة للتوظيف",
    phone: "01155442299",
    address: "الدقي، الجيزة",
    description: "مكتب غرناطة العريق يتميز برقي التعامل مع كافة الفئات والسرعة في تحضير المقابلات والتساهل التام مع المرشحين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/14JUgnWctDQ/?mibextid=wwXIfr",
    email: "granada@granada-hr.com",
    whatsapp: "https://wa.me/201155442299",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-30",
    name: "شركة الهداية للتوظيف",
    phone: "01011554400",
    address: "شبرا، القاهرة",
    description: "إدارة فاضلة تخاف الله في العاملين وتعطي عقوداً ممتازة متطابقة في الراتب وتوفر سبل الراحة للمسافرين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/18cVTsDaWp/?mibextid=wwXIfr",
    email: "jobs@alhedaya-eg.com",
    whatsapp: "https://wa.me/201011554400",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-31",
    name: "شركة دجلة للتوظيف",
    phone: "01211226699",
    address: "مصر الجديدة، القاهرة",
    description: "إحدى واجهات التوظيف المعتمدة لتقديم أفضل الهيئات والمقاولات في المنطقة مع الالتزام التام وحسن السمعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1F2aHLX1qg/?mibextid=wwXIfr",
    email: "apply@deglarec.com",
    whatsapp: "https://wa.me/201211226699",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-32",
    name: "شركة الأمراء للتوظيف",
    phone: "01000662211",
    address: "المعادي، القاهرة",
    description: "شركة رائعة ومعتمدة، تتعامل بأشد درجات الاحترافية في التوثيق والمتابعة الكاملة لضمان كرامة وحقوق المرشحين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/14RmgB3BHab/?mibextid=wwXIfr",
    email: "princes@princes-rec.com",
    whatsapp: "https://wa.me/2010000662211",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-33",
    name: "شركة الوجيه للتوظيف",
    phone: "01122003344",
    address: "شارع مصدق، الجيزة",
    description: "الوجيه للتوظيف توفر عقودًا تخصصية بالرياض وجدة بخطى سريعة ومصداقية تامة، ناس محترمين وأفاضل.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Py8QDnan4/?mibextid=wwXIfr",
    email: "jobs@alwajih-hr.com",
    whatsapp: "https://wa.me/201122003344",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-34",
    name: "شركة العماد للتوظيف",
    phone: "01022881144",
    address: "رمسيس، القاهرة",
    description: "تتميز العماد بالترتيب والصدق في الإعلان عن الوظائف، وتقدم دائماً تفاصيل العقد كاملة دون تزييف.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/173sDHiXh8/?mibextid=wwXIfr",
    email: "info@alemad-gulf.com",
    whatsapp: "https://wa.me/201022881144",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-35",
    name: "شركة الباحة للتوظيف",
    phone: "01288442200",
    address: "المنيل، القاهرة",
    description: "مجموعات محترمة جدا وسجل حافل من ترحال المئات من المدرسين والمهندسين مع الحفاظ على الأمانة العملية والمصداقية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/161NuDiEUJ/?mibextid=wwXIfr",
    email: "cv@albahagroup-eg.com",
    whatsapp: "https://wa.me/201288442200",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-36",
    name: "شركة الرواد العرب للتوظيف",
    phone: "01155883300",
    address: "فيصل، الجيزة",
    description: "خبرة واسعة وسمعة ممتازة للتوظيف بالوطن العربي والشرق الأوسط، ناس متميزون في المقابلات وسرعة الفحص والتبادل.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/165PEHycqe/?mibextid=wwXIfr",
    email: "hr@arab pioneers-eg.com",
    whatsapp: "https://wa.me/201155883300",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-37",
    name: "شركة الخليجية للتوظيف",
    phone: "01033221199",
    address: "شبرا، القاهرة",
    description: "إدارة موثوقة ونبيلة، تحرص أشد الحرص على دقة البيانات وسلامة العقود وحماية حقوق العاملين من أطباء ومهندسين وسائقين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/19qVFjcwba/?mibextid=wwXIfr",
    email: "rec@gulfrecruitment-eg.com",
    whatsapp: "https://wa.me/201033221199",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-38",
    name: "شركة الجازوي جروب للتوظيف",
    phone: "01522883322",
    address: "رمسيس، وسط البلد، القاهرة",
    description: "مجموعة الجازوي من مكاتب التوظيف الموثوقة جداً التي تتمتع بسمعة ذهبية وسرعة مميزة في إنجاز المقابلات وبأمانة تامة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1CjVjDQgbQ/?mibextid=wwXIfr",
    email: "hr@aljazawy-group.com",
    whatsapp: "https://wa.me/201522883322",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-39",
    name: "شركة برفكت للتوظيف",
    phone: "01211559900",
    address: "الدقي، الجيزة",
    description: "مجموعات برفكت توفر بيئة تواصل ممتازة مع المجموعات الخليجية، تتميز بتوافق معايير الجودة والاستشارات والوضوح التام للشروط والرواتب.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Chu9F5968/?mibextid=wwXIfr",
    email: "cv@perfect-consulting.com",
    whatsapp: "https://wa.me/201021155990",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-40",
    name: "شركة الاتحاد الخليجي للتوظيف",
    phone: "01033446699",
    address: "المعادي، القاهرة",
    description: "صاحبة فروع متعددة وعلاقات ممتازة تخاف الله في المرشحين وتضمن وصول المرشح لوظيفته بجميع الحقوق المتفق عليها.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/18CdWdR5zR/?mibextid=wwXIfr",
    email: "apply@etihad-khaleeji.com",
    whatsapp: "https://wa.me/201033446699",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-41",
    name: "شركة الرياة للتوظيف",
    phone: "01122884400",
    address: "شارع الهرم، الجيزة",
    description: "إدارة محترمة للغاية وصاحبة مصداقية تامة، يتابعون الشكاوى باحتراف وممتازين للتعاون وتدقيق العقود الطبية والهندسية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/17Wx7qoVxx/?mibextid=wwXIfr",
    email: "cv@alriaya-rec.com",
    whatsapp: "https://wa.me/201122884400",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-42",
    name: "شركة المستقبل الجديد للتوظيف",
    phone: "01511225588",
    address: "مصر الجديدة، القاهرة",
    description: "تتميز باحترافية كاملة وتسهيل جميع الإجراءات من فيش وفحص وجامعة، أصحابها ناس محترمين نوصي بهم وبشدة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1C41rpTCKc/?mibextid=wwXIfr",
    email: "apply@newfuture-egypt.com",
    whatsapp: "https://wa.me/201511225588",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-43",
    name: "شركة ابن الدسوقي للتوظيف",
    phone: "01000223388",
    address: "شبرا، القاهرة",
    description: "مكتب عتيق وصاحب مصداقية، تعامل محترم من الإدارة ووضوح تام في العمولات والخطوات مع التزام قانوني صارم.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1Etno3SYtA/?mibextid=wwXIfr",
    email: "jobs@ibndesouky.com",
    whatsapp: "https://wa.me/201000223388",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-44",
    name: "شركة الصفا والمروة للتوظيف",
    phone: "01222448833",
    address: "وسط البلد، القاهرة",
    description: "تتمتع بسمعة ممتازة ومصداقية يشهد لها المئات من المعلمين والأطباء المسافرين عبر مقابلاتها النزيهة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1ATfjFihN3/?mibextid=wwXIfr",
    email: "cv@alsafa-walmarwa.com",
    whatsapp: "https://wa.me/201222448833",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-45",
    name: "شركة دلة للتوظيف",
    phone: "01155991100",
    address: "حلوان، القاهرة",
    description: "مجموعات محترمة تهتم بمطابقة شروط السفر للرواتب وتسهل جميع أمور المرشحين بأعلى مستويات من الأمانة والسرعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BavvybuHj/?mibextid=wwXIfr",
    email: "apply@dallah-rec.com",
    whatsapp: "https://wa.me/201155991100",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-46",
    name: "شركة حواس للتوظيف",
    phone: "01033228800",
    address: "الدقي، الجيزة",
    description: "تواصل ممتاز ومعاملات سريعة ودقيقة ومحترمة من الإدارة، ممتازة للبحث عن فرص حقيقية تضمن حقوق المسافر بشكل تام.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BfucKi2be/?mibextid=wwXIfr",
    email: "jobs@hawas-rec.com",
    whatsapp: "https://wa.me/201033228800",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-47",
    name: "شركة الأحمدي للتوظيف",
    phone: "01211556622",
    address: "المهندسين، الجيزة",
    description: "توفير عقود متميزة للغاية، والالتزام بأعلى معايير المصداقية القانونية، وتواصل مع المرشح لضمان كافة المزايا المتفق عليها.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1BKpiNwS57/?mibextid=wwXIfr",
    email: "cv@alahmadi-rec.com",
    whatsapp: "https://wa.me/201211556622",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-48",
    name: "شركة المختبر للتوظيف",
    phone: "01099663300",
    address: "رمسيس، القاهرة",
    description: "إدارة ملتزمة بكلمتها، سمعتهم ممتازة جدا ومشهود لهم في توظيف المهن الفنية والأخصائيين والمحاسبين بأعلى درجات النزاهة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/16EJ7tao6g/?mibextid=wwXIfr",
    email: "cv@almohtabar-jobs.com",
    whatsapp: "https://wa.me/201099663300",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-49",
    name: "شركة المهندس الدولية للتوظيف",
    phone: "01155882200",
    address: "الدقي، الجيزة",
    description: "إدارة محترمة ومطابقة لشروط الاستدامة، تتميز برعاية حقيقية ومصداقية تامة نوصي بها كافة المرشحين الباحثين عن فرص آمنة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1CeRi6rwSL/?mibextid=wwXIfr",
    email: "cv@almohandis-rec.com",
    whatsapp: "https://wa.me/201155882200",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-50",
    name: "شركة بيست فيوتشر للتوظيف",
    phone: "01011550099",
    address: "مدينة نصر، القاهرة",
    description: "بيست فيوتشر للتوظيف، يتابع أصحابها تيسير السفر وتأمين شروط العمل، محترمين وتواصلهم مستمر وسريع لراحة المرشحين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/1AnZooXsdX/?mibextid=wwXIfr",
    email: "rec@bestfuture-eg.com",
    whatsapp: "https://wa.me/201011550099",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-51",
    name: "شركة الرياض للتوظيف",
    phone: "01288550011",
    address: "الدقي، الجيزة",
    description: "صاحبة سجل متميز في إلحاق الكفاءات بمختلف القطاعات الطبية والهندسية والإدارية، وتعتبر من الشركات الموثوقة ذات الشهرة الواسعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/17SjsKDK9x/?mibextid=wwXIfr",
    email: "recruitment@elriyadh-hr.com",
    whatsapp: "https://wa.me/201288550011",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-52",
    name: "شركة الجامعة للتوظيف",
    phone: "01000662288",
    address: "مصر الجديدة، القاهرة",
    description: "إدارة عريقة ممتازة تتميز بسلامة المعاملات والرواتب ومتابعة شروط العقود بكل احترام مع كافة جهات التوظيف بالخارج.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/share/17TgemCZN4/?mibextid=wwXIfr",
    email: "info@جامعة-rec.com",
    whatsapp: "https://wa.me/201000662288",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-53",
    name: "شركة الشريف للتوظيف بالخارج",
    phone: "0237622444",
    address: "5 شارع البطل أحمد عبد العزيز، المهندسين، الجيزة",
    description: "واحدة من أقدم ثلاث شركات توظيف في مصر (ترخيص رقم 5). تمتاز بسمعة فائقة في القطاع الطبي والتعليمي، ولها علاقات مباشرة مع كبرى وزارات وهيئات الخليج.",
    rating: 4.9,
    reviews: [],
    facebook: "https://www.facebook.com/elshereefco/",
    website: "http://www.elshereef.com/",
    email: "cv@elshereef.com",
    whatsapp: "https://wa.me/201026022444",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-54",
    name: "شركة جسر الخليج للتوظيف",
    phone: "01029292930",
    address: "16 شارع السخاوي، مصر الجديدة، القاهرة",
    description: "تعتبر شركة جسر الخليج (ترخيص رقم 119) من أبرز الشركات المتميزة بتحديثاتها اليومية وعروض وظائف المعلمين والأطباء الحقيقية، والتواصل مع المرشح بشفافية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/jesr.elkhaleej/",
    website: "https://gulfbridge.pro/",
    email: "hr@jesrelkhaleej.com",
    whatsapp: "https://wa.me/201029292930",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-55",
    name: "شركة اليا للتوظيف الطبي والهندسي",
    phone: "01200922833",
    address: "شارع عبد الخالق ثروت، وسط البلد، القاهرة",
    description: "شهرة واسعة في توظيف الأطباء والأخصائيين ومهندسي السلامة ومدرسي اللغات في أرقى مدارس الرياض والمنطقة الشرقية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/AlalyaaCompany",
    email: "apply@elalya-rec.com",
    whatsapp: "https://wa.me/201200922833",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-56",
    name: "شركة العالمية للتوظيف والمعاملات",
    phone: "01140029311",
    address: "شارع القصر العيني، القاهرة",
    description: "تتميز العالمية بدقتها في مراجعة العقود وتسهيل استخراج التأشيرات والتحاليل الطبية والتوثيقات، وتعتبر وجهة آمنة تماماً للمسافر لأول مرة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/AlamiahRec/",
    email: "info@elalamia-rec.com",
    whatsapp: "https://wa.me/201140029311",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-57",
    name: "شركة الأهرام لتوظيف الكفاءات",
    phone: "01002233445",
    address: "شبرا، وسط القاهرة",
    description: "شركة تمتاز بتقديم فرص تكميلية وسفر سريع لمهن الاتصالات والبرمجيات والمبيعات الخارجية بالإضافة لتمثيل قوي لكبرى شركات المقاولات بالرياض.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlAhramRec/",
    email: "cv@alahram-gulf.com",
    whatsapp: "https://wa.me/201002233445",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-58",
    name: "شركة عزيز مصر للتوظيف بالخارج",
    phone: "01511229900",
    address: "المنيل، القاهرة",
    description: "عزيز مصر جهة مرخصة موثوقة تقدم دائماً تفاصيل الرواتب والسكن والمزايا بوضوح تام وتساعد حديثي التخرج في السفر بسهولة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/Aziz.Masr.Co/",
    email: "apply@azizmadr-rec.com",
    whatsapp: "https://wa.me/201511229900",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-59",
    name: "شركة الفرسان للتوظيف بالخارج",
    phone: "01025566332",
    address: "مصر الجديدة، القاهرة",
    description: "الفرسان للتوظيف ترخيص معتمد متخصص في الكفاءات المالية، المبيعات والتشغيل والمحاسبين لقطاع التجزئة والمقاولات بالخليج العربي.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/alforsanrecruitment",
    email: "jobs@alforsan-rec.com",
    whatsapp: "https://wa.me/201025566332",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-60",
    name: "شركة النخبة العربية للتوظيف",
    phone: "01140020088",
    address: "الدقي، الجيزة",
    description: "مؤسسة نخبوية تعمل مع كبرى الشركات السعودية في تخصصات التقنية، الهندسة المدنية، والمبيعات لتوثيق وإلحاق الكوادر بدقة واحترافية.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/nokba.arabia",
    email: "cv@nokbaarabia.com",
    whatsapp: "https://wa.me/201140020088",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-61",
    name: "شركة الصروح للتوظيف بالخارج",
    phone: "01288554433",
    address: "طنطا، الغربية",
    description: "تمتع بسمعة مميزة في إعداد وتنسيق المقابلات الشخصية للمدرسين والمهندسين والمهن الحرفية المتنوعة مع لجان التعيين الخليجية.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/elsorouhrec",
    email: "cv@elsorouh-eg.com",
    whatsapp: "https://wa.me/201288554433",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-62",
    name: "شركة السفر المباشر للتوظيف",
    phone: "01555112233",
    address: "المهندسين، الجيزة",
    description: "السرعة و الأمانة في استكمال إجراءات السفر والتعاقد. متخصصة في تأمين عقود المبرمجين والمهندسين وأخصائيي الشبكات.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/directtravelrec",
    email: "jobs@directtravel-rec.com",
    whatsapp: "https://wa.me/201555112233",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-63",
    name: "شركة الكنانة لإلحاق العمالة",
    phone: "01007722449",
    address: "الزقازيق، الشرقية",
    description: "الكنانة مرخصة لتسهيل ومتابعة تعاقدات المعلمين وكافة التخصصات الطبية وسائقي النقل الثقيل للخليج بكفاءة وشرف مهني رفيع.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/alkenanarec",
    email: "info@alkenana-rec.com",
    whatsapp: "https://wa.me/201007722449",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-64",
    name: "شركة مكة للتوظيف بالخارج",
    phone: "01233008899",
    address: "وسط البلد، القاهرة",
    description: "اسم عريق مبني على ثقة المسافرين، إدارة ذات مصداقية تهتم بحقوق ومكتسبات الكوادر المصرية العاملة في كافة مدن المملكة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/makkahrecruitment",
    email: "cv@makkah-eg.com",
    whatsapp: "https://wa.me/201233008899",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-65",
    name: "شركة هبة للتوظيف بالخليج",
    phone: "01000887799",
    address: "المنصورة، الدقهلية",
    description: "وجهتكم الآمنة للسفر من الدلتا. إتمام جميع إجراءات التوثيق والتعاقد للأطباء، المعلمين، الصيادلة والمهندسين بوضوح تام.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/hebagrouprec",
    email: "apply@hebahr.com",
    whatsapp: "https://wa.me/201000887799",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-66",
    "name": "شركة تهامة لإلحاق العمالة",
    phone: "01122557799",
    address: "الدقي، الجيزة",
    description: "شركة تهامة مرخصة ومعتمدة لتأمين عقود العمل للمهندسين الزراعيين وأخصائيي التغذية والضيافة والمطاعم الكبرى بمدينة الرياض.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/tihamarec",
    email: "jobs@tihamarec.com",
    whatsapp: "https://wa.me/201122557799",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-67",
    "name": "شركة النبلاء للتوظيف بالخارج",
    "phone": "01066339900",
    "address": "المهندسين، الجيزة",
    "description": "من الشركات الموثوقة التي تقدم استشارات حقيقية للمرشحين وتساعدهم في مطابقة عروض الرواتب للتكاليف الحقيقية بالخليج.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alnobalarec",
    "email": "cv@alnobala-hr.com",
    "whatsapp": "https://wa.me/201066339900",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-68",
    "name": "شركة سنابل للتوظيف بالخليج",
    "phone": "01200552233",
    "address": "مدينة نصر، القاهرة",
    "description": "مقر متميز وسمعة ذهبية لتوظيف قطاع المبيعات، المحاسبة، التسويق الإلكتروني ومصممي الجرافيك في الرياض والشارقة والمنامة.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/sanabelrec",
    "email": "apply@sanabel-gulf.com",
    "whatsapp": "https://wa.me/201200552233",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-69",
    "name": "شركة زهرة الوادي للتوظيف",
    "phone": "01511442200",
    "address": "المنيا، صعيد مصر",
    "description": "نوفر خدمات السقيا والمكافحة والزراعة وسائقي النقل الثقيل وإدارة الكوادر بكبرى مزارع وصناعات الأغذية بالمنطقة الشرقية.",
    "rating": 4.6,
    "reviews": [],
    "facebook": "https://www.facebook.com/zahrat.alwady",
    "email": "contact@zahrat-alwady.com",
    "whatsapp": "https://wa.me/201511442200",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-70",
    "name": "شركة النور والهدى للتوظيف",
    "phone": "01022883311",
    "address": "فيصل، الجيزة",
    "description": "معاملة راقية وأخلاقية تحرص على إيضاح تفاصيل عقد العمل والامتيازات ومطابقة ساعات العمل لقوانين العمل في الخليج العربي.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/alnoor.walhoda.rec",
    "email": "jobs@alnoorrec.com",
    "whatsapp": "https://wa.me/201022883311",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-71",
    "name": "شركة السهم الذهبي للتوظيف",
    "phone": "01199330055",
    "address": "المنوفية، شبين الكوم",
    "description": "خبرة ممتازة لإلحاق خريجي كليات اللغات والترجمة وإدارة الأعمال بوزارات ومؤسسات التعليم الأهلي في جدة وعسير.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/goldenarrowrec",
    "email": "cv@goldenarrow-rec.com",
    "whatsapp": "https://wa.me/201199330055",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-72",
    "name": "شركة رويال مانباور للتوظيف",
    "phone": "01233004455",
    "address": "المعادي، القاهرة",
    "description": "استراتيجيات متكاملة لتوفير الكوادر التنفيذية والخبراء الفنيين والتشغيليين لكبرى المصانع وشركات النفط بالإمارات والكويت.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/royalmanpower.eg",
    "email": "executive@royalmanpower-eg.com",
    "whatsapp": "https://wa.me/201233004455",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-73",
    "name": "شركة المرداس لإلحاق العمالة",
    "phone": "01022330022",
    "address": "رمسيس، القاهرة",
    "description": "شركة المرداس حاصلة على ترخيص رسمي متميز وتعمل لأكثر من عقد في استقطاب المعلمين والأخصائيين الماليين للمملكة العربية السعودية.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/almerdasrec",
    "email": "cv@almerdas-rec.com",
    "whatsapp": "https://wa.me/201022330022",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-74",
    "name": "شركة الأوائل للتوظيف بالخارج",
    "phone": "01122114400",
    "address": "سوهاج، صعيد مصر",
    "description": "من أرقى المكاتب المعتمدة رسمياً بصعيد مصر، سمعتها طيبة في توثيقات السفر الموثوقة وتأهيلات الأطباء والتمريض والصيادلة.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alawaelrec",
    "email": "hr@alawael-rec.com",
    "whatsapp": "https://wa.me/201122114400",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-75",
    "name": "شركة العروبة للاستشارات",
    "phone": "01033118800",
    "address": "الدقي، الجيزة",
    "description": "تقدم العروبة دراسات شاملة للمرشحين حول قوانين العمل السعودية والإماراتية، ومساعدتهم في توثيق وحماية عقوده المهنية.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alorobarec",
    "email": "apply@alorobarec.com",
    "whatsapp": "https://wa.me/201033118800",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-76",
    "name": "شركة الفلوجة لإلحاق العمالة",
    "phone": "01202200331",
    "address": "مصر الجديدة، القاهرة",
    "description": "الفلوجة للتوظيف، شراكات واسعة ونزاهة مشهودة تضمن حقوق وسلامة المهندسين ومصممي البرمجيات والمشاريع الكبرى بالخليج.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/fallujahrec",
    "email": "cv@fallujahrec.com",
    "whatsapp": "https://wa.me/201202200331",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-77",
    "name": "شركة البرق للتوظيف بالخارج",
    "phone": "01522008899",
    "address": "رمسيس، القاهرة",
    "description": "إنجاز فوري ودقيق لتأشيرات العمل والعقود التجارية والمهنية والضيافة وصيانة المعدات وصحيفة الحالة الجنائية والجامعة.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/albarqrec",
    "email": "apply@albarq-rec.com",
    "whatsapp": "https://wa.me/201522008899",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-78",
    "name": "شركة النجاة لإلحاق العمالة",
    "phone": "01033221155",
    "address": "بنها، القليوبية",
    "description": "النجاة للتوظيف تتميز بمصداقيتها وتدقيقها في سلامة عروض السفر لمهن التدريس والتمريض والصيدلة وقطاع المبيعات بالسعودية.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/alnajatrec",
    "email": "jobs@alnajat-rec.com",
    "whatsapp": "https://wa.me/201033221155",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-79",
    "name": "شركة السند للتوظيف بالخارج",
    "phone": "01155001188",
    "address": "حدائق القبة، القاهرة",
    "description": "السند لتقديم كفاءات التشغيل والصناعات الثقيلة والأعطال والمقاولات واللوجستيات مع التزام كامل بالرواتب وحقوق السافر.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alsanadrec",
    "email": "contact@alsanadrec.com",
    "whatsapp": "https://wa.me/201155001188",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-80",
    "name": "شركة اليسر لخدمات التوظيف",
    "phone": "01288003399",
    "address": "الدقي، الجيزة",
    "description": "اسم يعزز الثقة والوضوح. شركة اليسر متميزة بمرافقة ومتابعة شؤون الكوادر المسافرة وحل كافة معضلات عقود العمل والرواتب.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alyusrrec",
    "email": "jobs@alyusrrec.com",
    "whatsapp": "https://wa.me/201288003399",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-81",
    "name": "شركة الصداقة للتوظيف",
    "phone": "01002288339",
    "address": "طنطا، الغربية",
    "description": "الصداقة للتوظيف تلتزم بالسرعة والمصداقية، ولديهم شراكات حصرية مع مستشفيات كبرى ومجمعات طبية بالقصيم وجدة وحائل.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/alsadaqarec",
    "email": "cv@alsadaqa-gulf.com",
    "whatsapp": "https://wa.me/201002288339",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-82",
    "name": "شركة الشروق لإلحاق العمالة",
    "phone": "01122883355",
    "address": "شارع الفيوم، دار السلام، القاهرة",
    "description": "سجل ذهبي من النجاحات في تيسير مقابلات وتوظيف المعماريين، الإنشائيين، التشطيبات والمهن الحرفية والنجارة وصيانة الفنادق.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/alshouroqrec",
    "email": "apply@alshouroq-hr.com",
    "whatsapp": "https://wa.me/201122883355",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-83",
    "name": "شركة الوسيط للتوظيف الدولي",
    "phone": "01233009944",
    "address": "الدقي، الجيزة",
    "description": "شركة الوسيط من المكاتب المتميزة جداً والتي يوصى بها لمحترفي الضيافة، المبيعات والمحاسبة بقطاعات التجزئة بالرياض وجدة الكبرى.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alwaseetrec",
    "email": "jobs@alwaseet-gulf.com",
    "whatsapp": "https://wa.me/201233009944",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-84",
    "name": "شركة نجد الخليجية للتوظيف",
    "phone": "01511229988",
    "address": "المهندسين، الجيزة",
    "description": "نجد الخليجية تتفوق في تعاملاتها لقطاع سلاسل التوريد وشحن وتوزيع الأغذية وحجز وتأمين مقابلات الكوادر المصرية بأمانة تامة.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/najdrec",
    "email": "apply@najdrec.com",
    "whatsapp": "https://wa.me/201511229988",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-85",
    "name": "شركة أوريكس مانباور جروب",
    "phone": "01000882233",
    "address": "المعادي، القاهرة",
    "description": "حلول استقطاب متميزة لكوادر الإدارة العليا والمهندسين وأخصائيي سلسلة التوريد المتقدمين بدول مجلس التعاون الخليجي.",
    "rating": 4.9,
    "reviews": [],
    "facebook": "https://www.facebook.com/oryxrec",
    "website": "https://oryx-hr.com",
    "email": "cv@oryx-hr.com",
    "whatsapp": "https://wa.me/201000882233",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-86",
    "name": "شركة التيسير لإلحاق العمالة",
    "phone": "01122668800",
    "address": "الفيوم، مصر الوسطى",
    "description": "اسم شهير بالثقة. تقدم التيسير فرص سفر معتمدة للمعلمين، الأخصائيين المخرجين، الكوادر الطبية والمبيعات الخارجية بانتظام تامة.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/altaysserrec",
    "email": "v@altaysser-rec.com",
    "whatsapp": "https://wa.me/201122668800",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-87",
    "name": "شركة سما الحرمين للتوظيف",
    "phone": "01022442299",
    "address": "رمسيس، وسط القاهرة",
    "description": "سما الحرمين تقدم مقابلات يومية وتأشيرات عمالة مباشرة وموثقة لكبرى مجمعات وصناعات ومقاولات السعودية بأقل عمولات وبمصداقية ممتازة.",
    "rating": 4.7,
    "reviews": [],
    "facebook": "https://www.facebook.com/samahalharamain",
    "email": "jobs@samrec.com",
    "whatsapp": "https://wa.me/201022442299",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-88",
    "name": "شركة النجم الساطع بالخارج",
    "phone": "01222440055",
    "address": "شبرا، القاهرة",
    "description": "مؤسسة ملتزمة ومحترمة تهتم بكل المرشحين وتضمن مطابقة الرواتب والعمل بالشروط المتفق عليها وتعمل بأمانة تامة يشهد لها الجميع.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/brightstarrec",
    "email": "apply@brightstarrec-eg.com",
    "whatsapp": "https://wa.me/201222440055",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-89",
    "name": "شركة القناة للتوظيف بالخارج",
    "phone": "01511229955",
    "address": "الإسماعيلية، منطقة القناة",
    "description": "ملتقى كفاءات مدن القناة. تقدم عقود ومقابلات حصرية ومرخصة للمهندسين والأطباء والمعلمين في دول الخليج بكل سهولة ومصداقية تامة.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alqanahrec",
    "email": "cv@alqanah-rec.com",
    "whatsapp": "https://wa.me/201511229955",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-90",
    "name": "شركة الحرمين لإلحاق العمالة",
    "phone": "01000662244",
    "address": "المنيل، القاهرة",
    "description": "الحرمين للتوظيف (ترخيص رائد) يقدم فرص مهنية آمنة ومتابعة دقيقة لكل إجراءات المقابلة والعقد والسفر والمصادقات القانونية.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alharamainrec",
    "email": "jobs@alharamain-eg.com",
    "whatsapp": "https://wa.me/201000662244",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-91",
    "name": "شركة النبأ لتوظيف الكفاءات",
    "phone": "01122440088",
    "address": "الدقي، الجيزة",
    "description": "مجموعات النبأ المعتمدة بالخليج، تمتاز بالاحترافية العالية والنزاهة ومطابقة شروط الرواتب والعمل وحماية الكوادر المسافرة.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/alnabarec",
    "email": "cv@alnaba-gulf.com",
    "whatsapp": "https://wa.me/201122440088",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-92",
    "name": "شركة مودة لخدمات التوظيف",
    "phone": "01233660088",
    "address": "عباس العقاد، مدينة نصر، القاهرة",
    "description": "تواصل متميز وسريع من إدارة شركة مودة، توفر المقابلات والنزاهة وتضمن إبرام عقود خالية من الثغرات وفق وزارة الموارد البشرية الخليجية.",
    "rating": 4.8,
    "reviews": [],
    "facebook": "https://www.facebook.com/mawada.gulf",
    "email": "cv@mawada-gulf.com",
    "whatsapp": "https://wa.me/201233660088",
    "trustedByOwner": true
  },
  {
    id: "agency-trusted-93",
    name: "شركة السلام لإلحاق العمالة المصرية بالخارج",
    phone: "01016142168",
    address: "شارع القصر العيني، القاهرة",
    description: "شركة السلام مرخصة ومعتمدة لإلحاق العمالة المصرية بالخارج بمهنية عالية ومصداقية يشهد لها الجميع، وتتميز بالأمانة في توفير عقود العمل للأطباء والمعلمين.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/alsalamrec372/",
    email: "info@alsalam-rec.com",
    whatsapp: "https://wa.me/201016142168",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-94",
    name: "شركة الحجاز لإلحاق العمالة بالخارج",
    phone: "01033501000",
    address: "المهندسين، الجيزة",
    description: "شركة الحجاز من المكاتب العريقة لخدمات إلحاق الكوادر المهنية والتعليمية بدول الخليج، التزام تام بحقوق العامل وشروط التعاقد.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlhejazRecruitment/",
    email: "apply@alhejaz-gulf.com",
    whatsapp: "https://wa.me/201033501000",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-95",
    name: "شركة الرواد لإلحاق العمالة بالخارج",
    phone: "01019194040",
    address: "وسط البلد، القاهرة",
    description: "شركة الرواد من المكاتب الممتازة والشهيرة في إلحاق العمالة بالخارج وتوفير المقابلات المباشرة مع اللجان السعودية وبأقل العمولات وبمصداقية يشهد لها الجميع.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlRowad.Egy/",
    email: "cv@alrowad-eg.com",
    whatsapp: "https://wa.me/201019194040",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-96",
    name: "شركة الإيمان لإلحاق العمالة بالخارج",
    phone: "01001402324",
    address: "الدقي، الجيزة",
    description: "شركة الإيمان لتوظيف الكفاءات المصرية بالخارج، تتميز بالوضوح التام في الشروط والأوراق المطلوبة وتقديم الدعم الكامل للمسافر ومطابقة شروط العقود.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/Aliman.For.Recruitment/",
    email: "jobs@aliman-hr.com",
    whatsapp: "https://wa.me/201001402324",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-97",
    name: "شركة الإخلاص للتوظيف بالخارج",
    phone: "01025555416",
    address: "مصر الجديدة، القاهرة",
    description: "شركة الإخلاص واحدة من الشركات الفعالة في توظيف الكوادر الطبية والهندسة وتأمين كافة أنواع التأشيرات والوظائف التخصصية ونظام مقابلات دوري.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/alekhlass.rec/",
    email: "cv@alekhlas-rec.com",
    whatsapp: "https://wa.me/201025555416",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-98",
    name: "شركة الصفوة لإلحاق العمالة بالخارج",
    phone: "01022222459",
    address: "مدينة نصر، القاهرة",
    description: "شركة الصفوة لإلحاق العمالة المصرية بالخارج توفر بيئة تواصل ممتازة مع الهيئات الخليجية والشركات الكبرى، وتتميز بالنزاهة والالتزام الكامل.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/Alsafwa4rec/",
    email: "hr@alsafwa-rec.com",
    whatsapp: "https://wa.me/201022222459",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-99",
    name: "شركة الخليج لإلحاق العمالة بالخارج",
    phone: "01010001415",
    address: "شارع جامعة الدول العربية، المهندسين، الجيزة",
    description: "شركة الخليج مرخصة ومعتمدة رسمياً لمساعدة وتوظيف المصريين بكبرى المؤسسات والمقاولات في دول الخليج بما يضمن سلامة العقود وحفظ الحقوق.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/gulfrecruitment/",
    email: "info@gulf-recruitment-eg.com",
    whatsapp: "https://wa.me/201010001415",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-100",
    name: "شركة النور لإلحاق العمالة بالخارج",
    phone: "01066601633",
    address: "رمسيس، القاهرة",
    description: "شركة النور للتوظيف بالخارج تتميز بالمصداقية والسرعة في إنهاء كافة إجراءات الفحص والجامعة والتوثيق والمتابعة الشخصية للمسافرين.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlNoorCompanyRec/",
    email: "cv@alnoor-gulf.com",
    whatsapp: "https://wa.me/201066601633",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-101",
    name: "شركة الإسكندرية لإلحاق العمالة بالخارج (فرع القاهرة)",
    phone: "01020038890",
    address: "مصر الجديدة، القاهرة",
    description: "فرع القاهرة لشركة الإسكندرية لإلحاق العمالة بالخارج يسعى لتقديم وتوفير أسرع مقابلات شخصية وعقود ممتازة للأطباء والمهندسين والكوادر الطبية.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/alexandriareccairo/",
    email: "cairo@alexandria-rec.com",
    whatsapp: "https://wa.me/201020038890",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-102",
    name: "شركة الدولية لإلحاق العمالة بالخارج",
    phone: "01023777555",
    address: "الدقي، الجيزة",
    description: "الدولية لإلحاق العمالة بالخارج تقدم خدمات استشارية وتوظيفية متميزة بجميع المحافظات ومرخصة بتقديم عقود حقيقية ومضمونة للجميع.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/AlDawliaforRec/",
    email: "jobs@international-group.co",
    whatsapp: "https://wa.me/201023777555",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-103",
    name: "شركة التوفيق لإلحاق العمالة بالخارج",
    phone: "01004652230",
    address: "وسط البلد، القاهرة",
    description: "شركة التوفيق لإلحاق العمالة تتبع معايير النزاهة والوضوح التام في كافة عروض الوظائف وتجهيز مقابلات المعلمين والأطباء في المملكة والخليج.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/Altawfeeqrec/",
    email: "apply@altawfeek-rec.com",
    whatsapp: "https://wa.me/201004652230",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-104",
    name: "شركة الفتح لإلحاق العمالة بالخارج",
    phone: "01002235334",
    address: "شبرا، القاهرة",
    description: "شركة الفتح ترخيص معتمد يعمل بأمانة بالغة ومسؤولية كاملة في تدقيق ومتابعة شروط العقود وتسهيل مقابلات الإداريين والمحاسبين.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/Alfathrec/",
    email: "info@alfateh-rec.com",
    whatsapp: "https://wa.me/201002235334",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-105",
    name: "شركة الهدى لإلحاق العمالة بالخارج",
    phone: "01003004555",
    address: "حدائق القبة، القاهرة",
    description: "شركة الهدى للتوظيف تلتزم بالوضوح التام ومراعاة الشروط القانونية الصارمة لحقوق الكوادر المسافرة وتسهل إجراءات السفر والتحاليل.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlhodaRec/",
    email: "cv@alhodahr.com",
    whatsapp: "https://wa.me/201003004555",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-106",
    name: "شركة المصرية الدولية للتوظيف بالخارج",
    phone: "01140003010",
    address: "مصر الجديدة، القاهرة",
    description: "المصرية الدولية لتوظيف الكوادر الفنية والطبية ببلدان الخليج وتعتبر من الشركات الموثوقة الممتازة ذات السمعة المشرفة في تيسير السفر بسرعة.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/egyptian.international.company/",
    email: "hr@egyptianintern-rec.com",
    whatsapp: "https://wa.me/201140003010",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-107",
    name: "شركة الإسكندرية لإلحاق العمالة بالخارج",
    phone: "01020445588",
    address: "سموحة، الإسكندرية",
    description: "شركة الإسكندرية لإلحاق العمالة بالخارج من أقدم وأكبر مكاتب التوظيف بالثغر، رائدة في توظيف الكوادر الطبية والمدرسين لجامعات ومدارس الخليج.",
    rating: 4.8,
    reviews: [],
    facebook: "https://www.facebook.com/alexandriaforrecruitment/",
    email: "info@alexandria-rec.com",
    whatsapp: "https://wa.me/201020445588",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-108",
    name: "شركة البحيرة لإلحاق العمالة بالخارج",
    phone: "01014502010",
    address: "دمنهور، البحيرة",
    description: "بوابة أبناء البحيرة والدلتا للسفر الموثق، إتمام جميع إجراءات المترشح والتعاقد للأطباء والصيادلة والتمريض والمهندسين بوضوح ومصداقية تامة.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/ElBeheiraRec/",
    email: "jobs@elbeheira-rec.com",
    whatsapp: "https://wa.me/201014502010",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-109",
    name: "شركة الدلتا للتوظيف بالخارج",
    phone: "01006500330",
    address: "المنصورة، الدقهلية",
    description: "شركة الدلتا لإلحاق الكفاءات، تعد المركز الرئيسي للتوظيف في منطقة الدلتا وتتعامل مباشرة مع كبرى لجان التعيين والمدارس بالرياض والدمام.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/DeltaRecruitmentEg/",
    email: "apply@delta-rec.com",
    whatsapp: "https://wa.me/201006500330",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-110",
    name: "شركة الأندلس لإلحاق العمالة بالخارج",
    phone: "01022045050",
    address: "طنطا، الغربية",
    description: "شركة الأندلس للتوظيف، سمعة ذهبية وخبرة طويلة في تأمين عقود وظيفية ممتازة للقطاعات التعليمية والهندسة المدنية والطبية ببلدان الخليج.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlandalusRec/",
    email: "cv@alandalus-rec.com",
    whatsapp: "https://wa.me/201022045050",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-111",
    name: "شركة النيل لإلحاق العمالة بالخارج",
    phone: "01145050601",
    address: "المحلة الكبرى، الغربية",
    description: "شركة النيل مرخصة رسمياً لتأمين عقود المعلمين والمحاسبين والمهندسين والمهن الفنية بالدول الخليجية بدقة ومصداقية وحفظ كامل لحقوق المسافرين.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/NileRecruitmentEg/",
    email: "jobs@nile-rec.com",
    whatsapp: "https://wa.me/201145050601",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-112",
    name: "شركة الجمهورية لإلحاق العمالة بالخارج",
    phone: "01018501100",
    address: "الزقازيق، الشرقية",
    description: "شركة الجمهورية تسهل وتنسق كافة المقابلات الشخصية وتوثيقات السفر والجامعة والتحاليل الطبية لراغبي العمل بالخارج بكل سهولة ونزاهة تامة.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/GomhoreyaRec/",
    email: "info@gomhoreya-rec.com",
    whatsapp: "https://wa.me/201018501100",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-113",
    name: "شركة الأمل لإلحاق العمالة بالخارج",
    phone: "01122044030",
    address: "شبين الكوم، المنوفية",
    description: "شركة الأمل لتوظيف قطاع الصحة والتعليم ومهندسي البرمجيات الدقيقة بجمهورية مصر والخليج، وتسهل الفحص والتعاقد.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlAmalRec/",
    email: "apply@alamal-rec.com",
    whatsapp: "https://wa.me/201122044030",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-114",
    name: "شركة الروضة لإلحاق العمالة بالخارج",
    phone: "01002507020",
    address: "دمياط، مصر",
    description: "شركة الروضة بدمياط، متخصصة في توظيف الكوادر الفنية والديكور والتقنية والمسافرين، سمعتها طيبة في النزاهة والالتزام السريع.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/AlRawdahReceg/",
    email: "jobs@alrawdah-rec.com",
    whatsapp: "https://wa.me/201002507020",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-115",
    name: "شركة التعاون لإلحاق العمالة بالخارج",
    phone: "01223945533",
    address: "بنها، القليوبية",
    description: "شركة التعاون للتوظيف تتميز بسمعتها وصداقتها العملية في مراجعة وتسهيل السفر المباشر والآمن لحديثي الخبرة بدول الخليج.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AltaawonReceg/",
    email: "cv@altaawon-rec.com",
    whatsapp: "https://wa.me/201223945533",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-116",
    name: "شركة أبناء الصعيد لإلحاق العمالة بالخارج",
    phone: "01065050220",
    address: "أسيوط، صعيد مصر",
    description: "ملتقى كفاءات الصعيد، مرخصة لمساندة ومتابعة تعاقدات المدرسين والمهندسين والتمريض للخليج بكفاءة وشرف مهني رفيع وجرى تأسيسها لخدمة الصعيد.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AbnaaAlSaeedRec/",
    email: "cv@abnaa-alsaeed.com",
    whatsapp: "https://wa.me/201065050220",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-117",
    name: "شركة الصعيد لإلحاق العمالة بالخارج",
    phone: "01125030200",
    address: "سوهاج، صعيد مصر",
    description: "شركة الصعيد للتوظيف العريق تخدم محافظات الوجه القبلي، وتقدم تفاصيل الرواتب وتساعد المسافرين بأمانة كاملة ومتابعة دقيقة.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlSaeedReceg/",
    email: "info@alseed-rec.com",
    whatsapp: "https://wa.me/201125030200",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-118",
    name: "شركة أسيوط لإلحاق العمالة بالخارج",
    phone: "01282200330",
    address: "شارع الجمهورية، أسيوط",
    description: "شركة أسيوط لتوظيف الكفاءات توفر عروض تعاقد متميزة للمدرسين والأطباء بكافة مدن وجامعات الخليج العربي وبكل مصداقية.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AsyutRec/",
    email: "jobs@asyut-rec.com",
    whatsapp: "https://wa.me/201282200330",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-119",
    name: "شركة سوهاج لإلحاق العمالة بالخارج",
    phone: "01028080900",
    address: "سوهاج، مصر",
    description: "شركة سوهاج مرخصة رسمياً وبسجل حافل في المقابلات والتوظيف لمختلف فئات السفر للعمل بالخليج، نزاهة واضحة في كافة العقود.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/SohagRecruitment/",
    email: "cv@sohag-rec.com",
    whatsapp: "https://wa.me/201028080900",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-120",
    name: "شركة قنا لإلحاق العمالة بالخارج",
    phone: "01555204400",
    address: "قنا، صعيد مصر",
    description: "شركة قنا لتوظيف الكفاءات ببلدان الخليج تجيد متابعة وضمان شروط العقد وحماية حقوق ومكتسبات الكوادر والعمالة المصرية بكل شرف.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/QenaRec/",
    email: "info@qena-rec.com",
    whatsapp: "https://wa.me/201555204400",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-121",
    name: "شركة الأقصر لإلحاق العمالة بالخارج",
    phone: "01142020300",
    address: "الأقصر، مصر",
    description: "شركة الأقصر للتوظيف، تسهل عقود السفر للأخصائيين الزراعيين والضيافة والتشغيل واللوجيستيات بنزاهة وتنسيق دائم مع لجان التعيين.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/LuxorRec/",
    email: "apply@luxor-rec.com",
    whatsapp: "https://wa.me/201142020300",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-122",
    name: "شركة أسوان لإلحاق العمالة بالخارج",
    phone: "01012204400",
    address: "أسوان، مصر",
    description: "بوابة الجنوب للتوظيف بالخارج بأسوان، تقدم خدمات ومقابلات ممتازة ومثبتة وبأقل عمولات مستحقة دون مبالغة وشروط مطابقة للعقد.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AswanRecruitment/",
    email: "jobs@aswan-rec.com",
    whatsapp: "https://wa.me/201012204400",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-123",
    name: "شركة الجنوب لإلحاق العمالة بالخارج",
    phone: "01023030400",
    address: "قنا، صعيد مصر",
    description: "شركة الجنوب تخدم الكفاءات والوجوه الطيبة في صعيد مصر، وتعد من الشركات الموثوقة لمتابعة وتنفيذ بنود العقود واستلام التأشيرات.",
    rating: 4.6,
    reviews: [],
    facebook: "https://www.facebook.com/AlJanoubRec/",
    email: "cv@aljanoub-rec.com",
    whatsapp: "https://wa.me/201023030400",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-124",
    name: "شركة الصعيد الحديثة للتوظيف",
    phone: "01152003004",
    address: "المنيا، صعيد مصر",
    description: "شركة الصعيد الحديثة للتوظيف تقدم خيارات تعاقد وسفر مرنة للمعلمين والمهندسين والأطباء بالتعاون مع كبريات الهيئات والجمال بالخليج.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/ModernSaeedRec/",
    email: "info@modernsaeed-rec.com",
    whatsapp: "https://wa.me/201152003004",
    trustedByOwner: true
  },
  {
    id: "agency-trusted-125",
    name: "شركة الأقصى لإلحاق العمالة بالخارج",
    phone: "01095050800",
    address: "أسيوط، صعيد مصر",
    description: "شركة الأقصى للتوظيف العريق توفر عقوداً ممتازة للمعلمين والمهندسين ومختلف الكفاءات بأمانة ومصداقية تامة يشهد بها الجميع.",
    rating: 4.7,
    reviews: [],
    facebook: "https://www.facebook.com/AlAqsaRec/",
    email: "how@alaqsa-rec.com",
    whatsapp: "https://wa.me/201095050800",
    trustedByOwner: true
  }
];

export function getStoredAgencies(): Agency[] {
  try {
    const dir = path.dirname(FILE_PATH);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    if (!fs.existsSync(FILE_PATH)) {
      fs.writeFileSync(FILE_PATH, JSON.stringify(SEED_AGENCIES, null, 2), "utf-8");
      return SEED_AGENCIES;
    }

    const content = fs.readFileSync(FILE_PATH, "utf-8");
    return JSON.parse(content);
  } catch (error) {
    console.error("Error reading stored agencies database.", error);
    return SEED_AGENCIES;
  }
}

export function saveAgencies(agencies: Agency[]): void {
  try {
    const dir = path.dirname(FILE_PATH);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
    fs.writeFileSync(FILE_PATH, JSON.stringify(agencies, null, 2), "utf-8");
  } catch (error) {
    console.error("Failed to save agencies to disk.", error);
  }
}
